### ISSUE TITLE
 "No JVM shared library file (jvm.dll) found" issue and the display disorder about the web interface of "The MESSAGEix framework"

### ISSUE THREAD

**Issue by Robinson950619** [iiasa/message_ix#659]

**Comment by Robinson950619** [comment]
Dear contributors,
        I'm a fresh postgraduate who first contact with the MESSAGEix model and desire to grasp and develop it. Due to my limitted knowledge, I have met some issues when I installed message-ix on Anaconda and read the relevant contents on the web “The MESSAGEix framework”. Two issues might be as follows:

        The first one is that I have met the issue "No JVM shared library file (jvm.dll) found" when I tried to install the message-ix on Anaconda. When I tried it with 

-  conda config --prepend channels conda-forge

        I got 

- Warning: 'conda-forge' already in 'channels' list, moving to the top

        I thought that was OK and would not affect the installation of the message-ix, so I continued. When I wanted to check if the installation was successful, I tried it with 

- message-ix show-versions

        I got

- Traceback (most recent call last):
  File "C:\Users\dell\anaconda3\envs\message_env\Scripts\message-ix-script.py", line 9, in <module>
    sys.exit(main())
  File "C:\Users\dell\anaconda3\envs\message_env\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\dell\anaconda3\envs\message_env\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\dell\anaconda3\envs\message_env\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\dell\anaconda3\envs\message_env\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\dell\anaconda3\envs\message_env\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\dell\anaconda3\envs\message_env\lib\site-packages\ixmp\cli.py", line 111, in show_versions_cmd
    ixmp.show_versions()
  File "C:\Users\dell\anaconda3\envs\message_env\lib\site-packages\ixmp\utils.py", line 563, in show_versions
    info.append(("… JVM path", mod.getDefaultJVMPath()))
  File "C:\Users\dell\anaconda3\envs\message_env\lib\site-packages\jpype\_jvmfinder.py", line 74, in getDefaultJVMPath
    return finder.get_jvm_path()
  File "C:\Users\dell\anaconda3\envs\message_env\lib\site-packages\jpype\_jvmfinder.py", line 212, in get_jvm_path
    raise JVMNotFoundException("No JVM shared library file ({0}) "
jpype._jvmfinder.JVMNotFoundException: No JVM shared library file (jvm.dll) found. Try setting up the JAVA_HOME environment variable properly.

        This issue was very similar to the Fwitte's issue, and I have seen the solution from Khaeru, he said to try

- conda install message-ix==3.5

**Comment by Robinson950619** [comment]
Here are my conda list and message-ix platform list,
![image](https://user-images.githubusercontent.com/111039940/195536049-abfc6d61-20bc-46ad-9d89-e65562167b38.png)

**Comment by gidden** [comment]
Hi @Robinson950619 - first thank you for reporting this error. We have observed this infrequently with new users and would like to try our best to find a solution. Can you start by showing us the full output of `conda list` in your environment? You can do that by writing it to a file like

```
> conda list > conda_list.txt
```

and attaching that here. Thanks!

**Comment by gidden** [comment]
We have done a bit of digging (thank you @awais307 !). The current `ixmp` conda recipe picks up a newer version of `openjdk`:
```
openjdk                   17.0.3               h57928b3_2    conda-forge
```

We observe that with an older version of `openjdk`, `message-ix show-versions` works as expected on a colleagues computer 

```
openjdk                   11.0.9.1             h57928b3_1    conda-forge
```

We were able to show that with a fresh install and intentional downgrade, we can 'fix' the issue.

@Robinson950619 - if you do this as well, your issue should be fixed:

```
> conda install -c conda-forge openjdk==11.0.9.1
```

**Comment by Robinson950619** [comment]
Dear Gidden,
         Thank you so much for your suggestions in details! I think your solution worked so well. I believe the firrst issue about "No JVM shared library file (jvm.dll) found" has dealt with. I has downgraded the openjdk as what you said, and I got 

         ixmp:        3.5.0
         message_ix:  3.6.0
         message_ix_models: None
         message_data: None

         click:       8.1.3
         dask:        2022.9.2
         genno:       installed
         graphviz:    None
         jpype:       1.4.0
         … JVM path:  C:\Users\dell\anaconda3\envs\message_env\Library\bin\server\jvm.dll
         openpyxl:    3.0.10
         pandas:      1.5.0
         pint:        0.19.2
         xarray:      2022.9.0
         yaml:        6.0

         iam_units:   installed
         jupyter:     installed
         matplotlib:  3.6.1
         plotnine:    None
         pyam:        1.3.1

         GAMS:        'gams' executable not in PATH

         python:      3.10.6 | packaged by conda-forge | (main, Aug 22 2022, 20:30:19) [MSC v.1929 64 bit (AMD64)]
         python-bits: 64
         OS:          Windows
         OS-release:  10
         machine:     AMD64
         processor:   Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
         byteorder:   little
         LC_ALL:      None
         LANG:        None
         LOCALE:      ('Chinese (Simplified)_China', '936')

But I found two details which were different from the installation narrated video on Youtube. The first one is 
         
        plotnine:    None

Which is showned in Youtube video is 

        plotnine:    0.8.0

The second one is 

        GAMS:        'gams' executable not in PATH

Which is showned in Youtube video is 

         GAMS:        29.1.0

I'm not sure if if these two differences will affect subsequent runs of the model. I guess they would. Because when I started jupyter to run the [westeros_baseline.ipynb](http://localhost:8888/notebooks/iiasa-message_ix-0c6f075/tutorial/westeros/westeros_baseline.ipynb), I have gotten the error in the step **"scenario.solve()"**, like this
![image](https://user-images.githubusercontent.com/111039940/195765683-3e76644e-789b-4299-86a5-270f29ae3d69.png)
![image](https://user-images.githubusercontent.com/111039940/195765734-794f74f6-944e-4e6f-bc3d-b66d7e5e9f9b.png)

And also gotten the error in the step **"scenario.var("OBJ")["lvl"]"**, like this
![image](https://user-images.githubusercontent.com/111039940/195766053-232eac2c-357d-4241-8572-61f5577c6c66.png)
![image](https://user-images.githubusercontent.com/111039940/195766086-4fb98be4-9f57-441b-871c-798c82cef6c5.png)

As well the following step **"Ploting Results"** gotten the error named **"ComputationError"**, like this, for example

**Comment by gidden** [comment]
For future reference to others looking at this issue, @khaeru found the likely culprit in the openjdk feedstock: https://github.com/conda-forge/openjdk-feedstock/issues/107

**Comment by Robinson950619** [comment]
Thank you so much for your reply, Gidden. So I want to make sure about what you have suggeted on me. Do you mean that the installation of my GAMS may have some errors, so shall I re-install GAMS agian following the installation instructions?

**Comment by Robinson950619** [comment]
And thank you so much about what you have shared about the openjdk feedstock from Khaeru, I will read it carefully in details. If I get the solutions or still have some troubles, I would like to write to you. Thank you for your suggetions and instructions again. Have a nice day!

**Comment by gidden** [comment]
> Thank you so much for your reply, Gidden. So I want to make sure about what you have suggeted on me. Do you mean that the installation of my GAMS may have some errors, so shall I re-install GAMS agian following the installation instructions?

Your error indicates that the message library can not find the installed GAMS executable, so it would be good to check through the installation notes to make sure they were followed correctly. If this issue persists, could you open a new issue here, please? That way we can keep this discussion purely about the Java installation problem you ran into

**Comment by Robinson950619** [comment]
> 

Okay, I will. If I still meet some errors after I check through the installation notes of GAMS, I will open a new issue. Thank you so much for your suggestions and instructions. Have a nice day! Thank you!

**Comment by awais307** [comment]
Closing this issue as I understand the problem mentioned in issue has been resolved.

**Comment by khaeru** [comment]
> Closing this issue as I understand the problem mentioned in issue has been resolved.

@awais307, I would say we have a *mitigation* for this issue, but the root cause mentioned at https://github.com/iiasa/message_ix/issues/659#issuecomment-1278572419 continues to exist and so this may continue to affect users until it is addressed.

However, this affects message_ix only via ixmp and its JDBCBackend, so I opened a new issue with a concise description and linked back to this one. If users run into the problem, we can point them there.
